apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami
spec:
  commonName: whoami.k9s.itnotetk.com
  secretName: whoami-cert
  dnsNames:
    - whoami.k9s.itnotetk.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
