apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rancher-logo-cert
  namespace: whoami
spec:
  commonName: rancher-logo.k9s.itnotetk.com
  secretName: rancher-logo-cert
  dnsNames:
    - rancher-logo.k9s.itnotetk.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
